source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AeonKit_Example', :exclusive => true do
  pod 'AeonKit', :path => '../'
end

target 'AeonKit_Tests', :exclusive => true do
  pod 'AeonKit', :path => '../'

  
end
